controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation


  product_list:
    path: /products
    controller: App\Controller\ProductController::list
    methods: GET


  product_show:
    path: /products/{id}
    controller: App\Controller\ProductController::show
    methods: GET


